# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b47e8d5f488ca789fde151dfe81d729a28157a93d9cb8cbe83822d41a872a1b40a4cd3c3cd1bf5bda16beca5178710d7cbe9bac4d7323d2d45cd0ec9975c77a5

test:
  secret_key_base: 8c9e72044ae0c904a4457b3890986f9e343fdfa80e1cfdf8ab4dbeb366041e4e29afa23ddf7584e0c2fe3ad419c5b465505040399b457ccc8da46485ed3d1392

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
